  ---
name: Samuel
surname: Verevis
position: "Economist, MFAT"
address: "Covered California"
email: "bryan@bryanjenks.dev"
linkedin: "Samuel Verevis"
date: "`r format(Sys.time(), '%B %Y')`"
headcolor: #000075
aboutme: "I have been doing X,yA"
docname: CV
output: vitae::awesomecv
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,
                      warning = FALSE,
                      message = FALSE)
require(xfun)
packages <- c('vitae'     # The CV's LaTeX Template
             ,'tibble'    # Data structure for tribbles
             ,'magrittr'  # The Pipe %>%
             ,'here'      # Relative File Paths
             ,'readr'     # Data Loading
             ,'glue'      # String Manipulation
            )
xfun::pkg_attach2(packages, message = FALSE)
source(file = here("r","data.r"))
```

# Employment

```{r EMPLOYMENT}
work %>%
  detailed_entries(
    with = title,
    what = unit,
    why = detail,
    when = glue::glue("{startMonth} {startYear} --> {endMonth} {endYear}",.na = ""),
    where = where
  )
```

# Education

```{r EDUCATION}
edu %>%
  detailed_entries(
    with = inst,
    what = degree,
    why = detail,
    when = glue::glue("{startYear} --> {endYear}",.na = ""),
    where = where
  )
```

# Skills

```{r SKILLS}
skills %>%
  detailed_entries(
    with = area,
    what = skills
  )
```

# Honors

```{r HONORS}
honors %>%
  detailed_entries(
    with = area,
    what = accomplishment,
    why = detail,
    when = year,
    where = where
  )
```

# Projects

```{r PROJECTS}
projects %>%
  detailed_entries(
    with = area,
    what = accomplishment,
    why = detail,
    when = year,
    where = where
  )
```

# Works

```{r WORKS}
works %>%
  detailed_entries(
    with = area,
    what = accomplishment,
    why = detail,
    when = year,
    where = where
  )
```

\pagebreak

# Certifications

```{r CERTIFICATIONS}
certifications %>%
  detailed_entries(
    with = area,
    what = accomplishment,
    why = detail,
    when = year,
    where = where
  )
```

